### ISSUE TITLE
Kubernetes部署应用

### ISSUE THREAD

**Issue by guanhui07** [guanhui07/blog#776]
部署应用开始需要先定义预期状态，就是在yaml文件里声明具体的Kubernetes对象的各种预期的状态。然后让Kubernetes创建对象，之后它会始终驱动集群的当前状态向预期状态移动（比如有节点挂了，会新起节点替代挂掉的节点）。部署完应用后后我们还需要通过Service向外部暴露应用，这样才能访问运行在Kubernetes集群里的应用。

下面我们来一步步递进地执行这三个步骤。

开始之前我们需要启动一下Minikube

```
minikube start
```

在部署清单文件（deployment.yaml）中定义预期状态

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app-container
          image: kevinyan001/kube-go-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
```

Kubernetes Deployment 对象（清单文件的kind里指定的）表示运行在集群中的应用。文件里还指定了应用需要一个副本运行（replicas），以及运行的容器名和容器的镜像、资源大小等信息。

Deployment是Kubernetes对象的一种，还有其他很多种对象分别对应Kubernetes里的不同类型的资源。

部署应用
使用上面定义的deployment.yaml创建Deployment对象来运行Go应用程序的容器：

```
➜ kubectl create -f deployment.yaml
deployment.apps/my-go-app created

➜ kubectl get deployments
NAME        READY     UP-TO-DATE   AVAILABLE   AGE
my-go-app   1/1       1            1           24s

➜ kubectl get pods
NAME                         READY     STATUS    RESTARTS   AGE
my-go-app-5bb8767f6d-2pdtk   1/1       Running   0          43s
```

暴露应用
应用部署完后还不能从外部直接访问，需要把刚才Deployment对象运行的应用程序作为Kubernetes的一个Service对外暴露。

```
➜ kubectl expose deployment my-go-app --type=NodePort --name=go-app-svc --target-port=3000 
service/go-app-svc exposed

➜ kubectl get svc
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
go-app-svc   NodePort    10.104.190.231   <none>        3000:31425/TCP   40h
kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP          6d13h

➜ minikube ip
192.168.64.4
```

通过kubectl get svc查询Service可以得到主机的31425端口映射到了Kubernetes运行着应用的容器的3000端口。在浏览器里使用Kubernetes集群IP加NodePort即可访问到Kubernetes部署的Go应用程序。

打开浏览器通过192.168.64.4:31425（以自己实践时查到的IP和端口为准）访问应用程序定义的两个路由的结果如下：

今天的文章简单的总结了一下将应用程序部署到Kubernetes集群的步骤，Kubernetes里有很多种对象来代表其内部的各种资源，今天部署应用用到的Deployment就是其中的一种，kubectl会根据.yaml文件中的配置信息请求Kubernetes的apiServer创建各种对象，我们后续要做的就是继续研究清楚这些常用到的Kubernetes对象
